using JetBrains.Annotations;
using Modding;
using UnityEngine;
using UnityEngine.UI;
using static Modding.CanvasUtil;
using Object = UnityEngine.Object;
using Patch = Modding.Patches;

namespace MoreSaves
{
    [UsedImplicitly]
    public class MoreSaves : Mod,IGlobalSettings<Settings>,ICustomMenuMod
    {
        private const string VERSION = "0.4.6";
        internal static readonly string SavesFolder = Application.persistentDataPath;
        internal static readonly string BackupFolder = SavesFolder + "/Saves Backup (Generated by MoreSaves)";

        private static GameObject _canvas;

        internal static MoreSaves Instance;

        public static Text PageLabel;

        public override string GetVersion()
        {
            return VERSION;
        }

        public MenuScreen GetMenuScreen(MenuScreen modListMenu)
        {
            MenuScreen CustomMenu = ModMenu.CreateCustomMenu(modListMenu);
            ModMenu.AutoBackupSelector.menuSetting.RefreshValueFromGameSettings();
            return CustomMenu;
        }

        public static Settings settings { get; set; } = new Settings();
        public void OnLoadGlobal(Settings s) => MoreSaves.settings = s;
        public Settings OnSaveGlobal() => MoreSaves.settings;

        public override void Initialize()
        {
            if (Instance == null) Instance = this;
            Log("Initializing MoreSaves");

            CreateFonts();

            _canvas = CreateCanvas(RenderMode.ScreenSpaceOverlay, new Vector2(1920f, 1080f));

            PageLabel = CreateTextPanel
                (
                    _canvas, "Page 1/?", 29, TextAnchor.MiddleCenter,
                    new RectData
                    (
                        new Vector2(200f, 200f),
                        new Vector2(1240f, 870f),
                        new Vector2(0f, 0f),
                        new Vector2(0f, 0f)
                    )
                )
                .GetComponent<Text>();

            PageLabel.enabled = true;

            FadeOut(0f);
            _canvas.AddComponent<MoreSavesComponent>();
            Object.DontDestroyOnLoad(_canvas);
            Log("Initialized MoreSaves");

        }

        private static void FadeOut(float t)
        {
            PageLabel.CrossFadeAlpha(0f, t, true);
        }
    }
}
